version: '3.8'

services:
    db:
        image: mysql:8.0.35
        volumes:
            - mysql_db_volume:/var/lib/mysql
        env_file:
            - .env
    web:
        build: 
            context: ./
            dockerfile: ./docker/web/Dockerfile
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/app/static
            - uploads_volume:/app/uploads
            - configs_volume:/app/configs
        expose:
            - 8000
        env_file:
            - .env
        depends_on:
            - db
    nginx:
        build: ./docker/nginx
        volumes:
            - static_volume:/app/static
            - uploads_volume:/app/uploads
        ports:
            - 80:80
        depends_on:
            - web

volumes:
    mysql_db_volume:
    static_volume:
    uploads_volume:
    configs_volume: